services:
  # Graphiti Claude Code MCP Server
  graphiti-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-claude-code-mcp
    environment:
      # 1Password Service Account Token (CRITICAL: must be passed to container)
      # This is needed by the SDK inside the container, not just for op run
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN}

      # CRITICAL: Must match GTD Coach for bi-directional knowledge sharing
      - GRAPHITI_GROUP_ID=${GRAPHITI_GROUP_ID:-shared_knowledge}
      # Neo4j configuration
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j.graphiti.local:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      # Password retrieved from 1Password at runtime

      # Non-secret configuration values
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}

      # Fallback mode for when 1Password is unavailable
      - GRAPHITI_FALLBACK_MODE=${GRAPHITI_FALLBACK_MODE:-false}

      # Memory Configuration
      - GRAPHITI_BATCH_SIZE=${GRAPHITI_BATCH_SIZE:-5}
      - MEMORY_DECAY_FACTOR=${MEMORY_DECAY_FACTOR:-0.95}
      - MEMORY_INCLUDE_HISTORICAL=${MEMORY_INCLUDE_HISTORICAL:-false}
      - ENABLE_GTD_INTEGRATION=${ENABLE_GTD_INTEGRATION:-true}
      - ENABLE_CROSS_REFERENCES=${ENABLE_CROSS_REFERENCES:-true}

      # MCP Server Configuration
      - MCP_SERVER_NAME=graphiti-claude-code-mcp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # Langfuse Configuration (Non-secret values)
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://langfuse.local}
      - LANGFUSE_TRACING_ENABLED=${LANGFUSE_TRACING_ENABLED:-true}

      # OpenTelemetry Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://alloy.local:4317}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-graphiti.mcp}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER:-otlp}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER:-otlp}
      - OTEL_INSTRUMENTATION_ENABLED=${OTEL_INSTRUMENTATION_ENABLED:-true}

      # Adaptive Sampling Configuration
      - INFRASTRUCTURE_BASE_SAMPLE_RATE=${INFRASTRUCTURE_BASE_SAMPLE_RATE:-0.1}
      - INFRASTRUCTURE_MAX_SAMPLE_RATE=${INFRASTRUCTURE_MAX_SAMPLE_RATE:-1.0}
      - MEMORY_PRESSURE_THRESHOLD=${MEMORY_PRESSURE_THRESHOLD:-70}
      - LATENCY_THRESHOLD_SECONDS=${LATENCY_THRESHOLD_SECONDS:-5.0}
      - CASCADE_WINDOW_SECONDS=${CASCADE_WINDOW_SECONDS:-60}

      # SSL Configuration for OrbStack
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/orbstack-root.crt
      - REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/orbstack-root.crt

    volumes:
      # Mount local code for development
      - .:/app
      # Mount shared .env.graphiti
      - ${HOME}/gtd-coach/.env.graphiti:/app/.env.graphiti:ro
      # Mount Claude commands output directory
      - ${HOME}/.claude/commands:/root/.claude/commands
      # Mount Neo4j query logs for correlation (read-only)
      - ${HOME}/Documents/1_projects/graphiti-neo4j/neo4j/logs:/var/lib/neo4j/logs:ro

    ports:
      # MCP server port (if needed for debugging)
      - "5173:5173"

    networks:
      - graphiti-network

    command: python mcp_server.py

    # Limit restart attempts to prevent rapid rate limit consumption
    restart: on-failure:3

    # Neo4j runs in separate graphiti-neo4j project
    # No dependency needed here

    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; from secrets_manager import SecretsManager; asyncio.run(SecretsManager.get_instance())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Utility service for running Neo4j test commands
  test-runner:
    image: neo4j:5.26-community
    container_name: graphiti-test-runner
    networks:
      - graphiti-network
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo 'Test runner ready'"]

networks:
  graphiti-network:
    name: orbstack-shared
    external: true

# Note: This compose file assumes Neo4j is already running in the graphiti-neo4j project
# on port 7687 with proper authentication configured via 1Password
