version: '3.8'

services:
  # Test runner service for behavioral correlation tests
  test-behavioral:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-test-behavioral
    environment:
      # Test environment configuration
      - GRAPHITI_GROUP_ID=test_behavioral_correlation
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
      - NEO4J_DATABASE=neo4j

      # Use test API keys (non-production)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small

      # Test configuration
      - GRAPHITI_BATCH_SIZE=5
      - MEMORY_DECAY_FACTOR=0.97
      - MEMORY_INCLUDE_HISTORICAL=true
      - ENABLE_GTD_INTEGRATION=false  # Disable for isolated testing
      - ENABLE_CROSS_REFERENCES=true

      # Logging
      - LOG_LEVEL=DEBUG
      - PYTEST_VERBOSE=true

      # Disable external services for testing
      - GRAPHITI_FALLBACK_MODE=true
      - LANGFUSE_TRACING_ENABLED=false
      - OTEL_INSTRUMENTATION_ENABLED=false

    volumes:
      # Mount source code
      - .:/app
      # Mount test results
      - ./test-results:/app/test-results

    networks:
      - test-network

    command: |
      bash -c "
        echo 'Waiting for Neo4j to be ready...'
        sleep 10
        echo 'Running behavioral correlation tests...'
        python -m pytest tests/test_implicit_scoring_unit.py -v --tb=short --junitxml=/app/test-results/unit-results.xml
        python -m pytest tests/test_implicit_scoring_integration.py -v --tb=short -m integration --junitxml=/app/test-results/integration-results.xml
        echo 'Tests completed. Results saved to test-results/'
      "

    depends_on:
      - neo4j-test

  # Neo4j test instance with minimal configuration
  neo4j-test:
    image: neo4j:5.26-community
    container_name: graphiti-neo4j-test
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_initial__size=256m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

    volumes:
      # Use tmpfs for faster test execution
      - type: tmpfs
        target: /data
        tmpfs:
          size: 268435456  # 256MB

    ports:
      - "7688:7687"  # Different port to avoid conflicts
      - "7475:7474"  # Browser on different port

    networks:
      - test-network

    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpassword", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Unit test runner (no Neo4j needed)
  test-unit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-test-unit
    environment:
      - LOG_LEVEL=INFO
      - PYTEST_VERBOSE=true

    volumes:
      - .:/app
      - ./test-results:/app/test-results

    networks:
      - test-network

    command: |
      bash -c "
        echo 'Running unit tests...'
        python -m pytest tests/test_implicit_scoring_unit.py -v --tb=short \
          --cov=capture_extended --cov-report=html:/app/test-results/coverage \
          --junitxml=/app/test-results/unit-results.xml
        echo 'Unit tests completed'
      "

networks:
  test-network:
    driver: bridge

volumes:
  test-results:
